'use client'
import {RootStyleRegistry} from '@/modules/shared/components/root-style-registry'
import '@/styles/globals.css'
import {Poppins} from 'next/font/google'
import React from "react";

const poppins = Poppins({subsets: ['devanagari'], style: ["normal"], weight: "400"})

export const metadata = {
    title: 'Digisign API',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head><title>{metadata.title}</title></head>
        <body className={poppins.className}>
            <RootStyleRegistry>{children}</RootStyleRegistry>
        </body>
        </html>
    )
};
