import { RootStyleRegistry } from '@/modules/shared/components/root-style-registry'
import './styles/globals.css'
import {Inter} from 'next/font/google'
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Wahyu',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <RootStyleRegistry>{children}</RootStyleRegistry>
        </body>
        </html>
    )
};
