export const ParagraphTerms = [
    "Anda akan menggunakan Sertifikat Elektronik dan Tanda Tangan Elektronik untuk menandatanganani dokumen elektronik dengan PT xxxxxx . PT xxxxxx bekerja sama dengan PT Solusi Net Internusa (Digisign.id) selaku Penyelenggara Tanda Tangan Elektronik dan Penyelenggara Sertifikasi Elektronik Indonesia yang telah berinduk pada Kementerian Komunikasi dan Informatika Republik Indonesia dengan merk Digisign.id.\n",
    "Dengan ini, Anda menyatakan setuju untuk mendaftar sebagai pengguna platform Digisign.id dan diterbitkan sertifikat elektronik oleh PT Solusi Net Internusa (Digisign.id) atas nama Anda dalam rangka penggunaan layanan Tanda Tangan Elektronik di platform Digisign.id untuk menandatangani dokumen elektronik.\n",
    "Apabila data pribadi Anda terverifikasi kesesuaiannya, maka PT Solusi Net Internusa (Digisign.id) sebagai Penyelenggara Sertifikasi Elektronik berinduk oleh Kementerian Komunikasi dan Informatika Republik Indonesia, akan menerbitkan sertifikat elektronik sebagai bukti bahwa data pribadi Anda telah diverifikasi dan sesuai dengan data yang tercatat pada sistem instansi yang berhak mengeluarkan identitas tersebut.\n",
    "Oleh karenanya, Anda menjamin keakuratan data pribadi yang Anda sediakan dan setuju ataspemrosesan data pribadi Anda untuk tujuan penerbitan sertifikat elektronik serta layanan lain dari PT Solusi Net Internusa (Digisign.id) yang melekat pada sertifikat elektronik tersebut.\n",
    "Anda setuju untuk membebaskan PT Solusi Net Internusa (Digisign.id) dari tanggung jawab ganti kerugian, klaim atau gugatan atas hasil sertifikat elektronik yang diterbitkan apabila data yang diberikan yang tidak valid dan tidak benar.\n",
    "Dengan ini, Anda menyatakan secara jelas dan tanpa adanya paksaan, akan memberikan kuasa kepada PT xxxxxx untuk meneruskan data KTP, swafoto, nomor ponsel dan alamat surel Anda sebagai data pendaftaran kepada PT Solusi Net Internusa (Digisign.id) guna memenuhi ketentuan Peraturan Perundang-undangan, yaitu Peraturan Pemerintah Nomor 71 Tahun 2019 tentang Penyelenggara Sistem dan Transaksi Elektronik, dan Peraturan Kementerian Informasi dan Komunikasi Nomor 11 Tahun 2018.\n",
    "Dengan ini Anda telah membaca, memahami, dan setuju untuk terikat pada syarat dan ketentuan layanan Penyelenggara Sertifikat Elektronik yang terdapat pada Perjanjian Kepemilikan Sertifikat Elektronik (Subscriber Agreement), Kebijakan Privasi PSrE (CA Privacy Policy), serta Pernyataan Penyelenggaraan Sertifikat Elektronik (Certification Practice Statement) Digisign.id yang dapatdiakses melalui https://repository.digisign.id/.\n"
]
